name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: setup_buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        id: login_to_docker_hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: docker-compose.yml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aast-dms:latest
